name: Sync Wiki

on:
  push:
    branches: [main]
    paths: ['wiki/**']
  workflow_dispatch:

permissions:
  contents: write

jobs:
  sync-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync wiki
        run: |
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.wiki.git gh-wiki

          cd gh-wiki

          git config --global --add safe.directory "$(pwd)"
          git config user.name "Oleksii Lisikh"
          git config user.email "alisiikh@gmail.com"

          rm -rf *
          cp -r ../wiki/* .

          git add .
          git commit -m "action: wiki sync" || echo "No changes to commit"
          git push
